first homework done
bark93/ILFE-HW1 pull request #1
Opened 2017-02-15 22:33 UTC by bark93

2017-02-17 12:14 UTC, BertaFly commented on style-3.css
> +    line-height: 150%;
line-height: 150%; - зачем это здесь?

2017-02-17 12:16 UTC, BertaFly commented on style-3.css
> +    margin-left:0px;
это лишнее, картинка у тебя и так по центру.

2017-02-17 12:20 UTC, BertaFly reviewed
надо исправить мелочи. смотри коменты.

2017-02-20 11:19 UTC, bark93 commented on style-3.css
> +    line-height: 150%;
это межстрочный интервал же

2017-02-20 11:20 UTC, bark93 commented on style-3.css
> +    margin-left:0px;
принял к сведению

2017-02-20 12:46 UTC, BertaFly commented on style-3.css
> +    line-height: 150%;
Ок, согласна

2017-02-20 12:47 UTC, BertaFly approved these changes
Готово

2017-02-22 18:49 UTC, egemon requested changes
Исправляй и мерджи. Рад что разорался с ключом.

2017-02-22 18:49 UTC, egemon commented on index-3.html
> +      <!-- отличное название класса! так нужно всегда -->
Мои комменты в финальной версии можно смело удалять)

2017-02-22 20:06 UTC, merged