homework 2 is ready
bark93/ILFE-HW1 pull request #4
Opened 2017-02-27 15:06 UTC by bark93

2017-02-28 12:04 UTC, VladyslavAbramov commented on hw2/index-hw2.html
> +					<li><a href="#">Главная</a></li>
когда наводишь курсор на пункт li , все пункты справа смещаються на 2 ширины бордера. 
текст находится не в центре пункта.
кликабельный только сам текст, было бы неплохо, если область вокруг текста была тоже кликабельной.

2017-02-28 12:14 UTC, VladyslavAbramov commented on hw2/index-hw2.html
> +			<div class="main-text">
Лишний таб

2017-02-28 12:23 UTC, VladyslavAbramov commented on hw2/style-hw2.css
> +	display: inline-block;
при display: inline-block создаются пробелы между элементами, которые по сути не нужны

2017-02-28 23:04 UTC, bark93 commented on hw2/index-hw2.html
> +					<li><a href="#">Главная</a></li>
текст вроде и не должен, остальное сделал для всех менюшек

2017-02-28 23:04 UTC, bark93 commented on hw2/index-hw2.html
> +			<div class="main-text">
не вижу где(

2017-02-28 23:04 UTC, bark93 commented on hw2/style-hw2.css
> +	display: inline-block;
спасибо, исправил

2017-03-02 15:02 UTC, VladyslavAbramov approved these changes

2017-03-07 21:36 UTC, egemon requested changes

2017-03-07 21:36 UTC, egemon commented on hw2/index-hw2.html
> +		<header class="main-header">
gj

2017-03-07 21:36 UTC, egemon commented on hw2/index-hw2.html
> +		<aside class="products">
gj

2017-03-07 21:36 UTC, egemon commented on hw2/index-hw2.html
> +		<div class="clear"></div>
i don't like it. Find the better way.

2017-03-07 21:36 UTC, egemon commented on hw2/index-hw2.html
> +		<div class="clear"></div>
Wrap in container and add clearfix

2017-03-07 21:36 UTC, egemon commented on hw2/index-hw2.html
> +			<div class="footer-menu">
Do you think you need this wrapping div all around each UL? can we eliminate it?

2017-03-07 21:36 UTC, egemon commented on hw2/index-hw2.html
> +			<nav class="main-menu-flex">
aligning in HTML code

2017-03-07 21:36 UTC, egemon commented on hw2/style-hw2.css
> +	width: 100%;
do you need this?

2017-03-07 21:36 UTC, egemon commented on hw2/style-hw2.css
> +	font-family: sans-serif;
Try to find needed font, include it and use font-stack, Ask @bertaFly of @ValeeraCatcha

2017-03-07 21:36 UTC, egemon commented on hw2/style-hw2.css
> +	width: 100px;
do you need this?

2017-03-07 21:36 UTC, egemon commented on hw2/style-hw2.css
> +	border-bottom: 0px solid #c8c8c8;
0px solid #c8c8c8 heheheh seriusly?

2017-03-07 21:36 UTC, egemon commented on hw2/style-hw2.css
> +	vertical-align: top;
don't like it, find another way more natural.

2017-03-07 21:36 UTC, egemon commented on hw2/style-hw2.css
> +	overflow: hidden;
in menu I prefer to use clearfix, as far here could be dropdown that will be cut by this overflow

2017-03-07 21:36 UTC, egemon commented on hw2/style-hw2.css
> +	overflow: hidden;
why do you even need this? You don't have floats inside

2017-03-07 21:36 UTC, egemon commented on hw2/style-hw2.css
> +	position: absolute;
no way, it is a bad idea. Use floats-inlines-flex. Position was not created for that.

2017-03-07 21:36 UTC, egemon commented on hw2/style-hw2.css
> +	font-size: 90%;
Why 90%?

2017-03-07 21:36 UTC, egemon commented on hw2/style-hw2.css
> +	font-size: 90%;
Set font-size to parent as far as this property is inherited

2017-03-07 21:36 UTC, egemon commented on hw2/style-hw2.css
> +	width: 100%;
why?

2017-03-07 21:36 UTC, egemon commented on hw2/style-hw2.css
> +	font-family: sans-serif;
Set font-family to body, and all general font props to body and override if you need. It will make you code lesser.

2017-03-07 21:36 UTC, egemon commented on hw2/style-hw2.css
> +	width: 100px;
bad idea, don't use fixed width. Your site might have a lot of translations, so it would be better if menu items allow this

2017-03-07 21:36 UTC, egemon commented on hw2/style-hw2.css
> +	width: 100%;
everywhere

2017-03-07 21:36 UTC, egemon commented on hw2/style-hw2.css
> +	width: 100px;
here again

2017-03-07 23:31 UTC, bark93 commented on hw2/style-hw2.css
> +	width: 100%;
fixed

2017-03-07 23:31 UTC, bark93 commented on hw2/style-hw2.css
> +	width: 100px;
fixed

2017-03-07 23:31 UTC, bark93 commented on hw2/style-hw2.css
> +	width: 100%;
fixed

2017-03-07 23:31 UTC, bark93 commented on hw2/style-hw2.css
> +	font-family: sans-serif;
fixed

2017-03-07 23:31 UTC, bark93 commented on hw2/style-hw2.css
> +	width: 100%;
fixed

2017-03-07 23:31 UTC, bark93 commented on hw2/style-hw2.css
> +	font-size: 90%;
because it`s smaller then fonts in another menus.
done.

2017-03-07 23:31 UTC, bark93 commented on hw2/style-hw2.css
> +	position: absolute;
fixed. changed for flex

2017-03-07 23:31 UTC, bark93 commented on hw2/style-hw2.css
> +	overflow: hidden;
fixed. this was artefacts from the work process

2017-03-07 23:31 UTC, bark93 commented on hw2/style-hw2.css
> +	vertical-align: top;
fixed

2017-03-07 23:31 UTC, bark93 commented on hw2/style-hw2.css
> +	border-bottom: 0px solid #c8c8c8;
lol. fixed

2017-03-07 23:31 UTC, bark93 commented on hw2/style-hw2.css
> +	width: 100px;
fixed

2017-03-07 23:31 UTC, bark93 commented on hw2/style-hw2.css
> +	width: 100px;
fixed

2017-03-07 23:31 UTC, bark93 commented on hw2/style-hw2.css
> +	font-family: sans-serif;
i cant determine the exact font. i have used default fonts to describe properties

2017-03-07 23:31 UTC, bark93 commented on hw2/index-hw2.html
> +			<nav class="main-menu-flex">
fixed

2017-03-07 23:31 UTC, bark93 commented on hw2/index-hw2.html
> +			<div class="footer-menu">
fixed

2017-03-07 23:31 UTC, bark93 commented on hw2/index-hw2.html
> +		<div class="clear"></div>
added container and decided to use flex

2017-03-13 10:46 UTC, egemon commented on hw2/style-hw2.css
> +	display: block;
is that is not block li?

2017-03-13 10:47 UTC, egemon commented on hw2/style-hw2.css
> +	float: left;
you forget to clean flow after this float

2017-03-13 10:48 UTC, egemon commented on hw2/style-hw2.css
> +	padding: 10px;
don't use padding to align text vertically. Better use line-height. As far as font-size may change.

2017-03-13 10:49 UTC, egemon commented on hw2/style-hw2.css
> +.footer-menu__item:hover .footer-menu__link  {
link and item are pretty the same (by size), so you can  omit including selectors here

2017-03-13 10:50 UTC, egemon commented on hw2/style-hw2.css
> +	border-right: rgba(255,255,255,1) 1px solid;
don't use rgba if you don't need alfachannel

2017-03-13 10:50 UTC, egemon commented on hw2/style-hw2.css
> +.main-menu-flex li:hover {
use class name here instead of including selectors

2017-03-13 10:51 UTC, egemon approved these changes

2017-03-22 16:30 UTC, bark93 commented on hw2/style-hw2.css
> +	display: block;
fixed

2017-03-22 16:58 UTC, bark93 commented on hw2/style-hw2.css
> +	float: left;
fixed

2017-03-22 16:58 UTC, bark93 commented on hw2/style-hw2.css
> +	padding: 10px;
fixed for all

2017-03-22 16:58 UTC, bark93 commented on hw2/style-hw2.css
> +.footer-menu__item:hover .footer-menu__link  {
fixed

2017-03-22 16:58 UTC, bark93 commented on hw2/style-hw2.css
> +	border-right: rgba(255,255,255,1) 1px solid;
fixed

2017-03-22 16:58 UTC, bark93 commented on hw2/style-hw2.css
> +.main-menu-flex li:hover {
fixed

2017-03-22 17:04 UTC, merged